
server:
  port: ${PORT} # default port is 8761

spring:
  name: service-discovery

### --- Eureka Server Configurations --- ###
# you can read eureka server configuration here: https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-eureka-server.html
eureka:
  instance:
    hostname: ${HOST_NAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
<<<<<<< HEAD
=======
    serviceUrl:
      # specify where services can discover eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
>>>>>>> feature/no-ref/service-discovery
